title: "Ciencia de Redes"
author: "Carlos Francisco Betancourt y Luis Guillermo García Jácome"
copyright: "2022"
logo: "logo-pagina-02.png"

execute:
    execute_notebooks: off # auto, force, cache, off

html:
    favicon: "favicon.ico"
    extra_navbar: "Hecho con <a href='https://jupyterbook.org'>Jupyter Book</a>"
    home_page_in_navbar: false

repository:
  url: https://github.com/Curso-Redes-F-Ciencias-UNAM/ciencia-de-redes
  path_to_book: src/
  branch: main

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

sphinx:
    config:
        html_theme: sphinx_book_theme
        # html_theme: furo
        # html_theme: basic
        # html_theme_path: ../
        language: es
        bibtex_reference_style: author_year
        # html_sidebars: { '**': ['globaltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html'] }
        html_static_path: ['_static']
        html_theme_options: { 'search_bar_text': "Buscar..." }


bibtex_bibfiles:
    - references.bib
